<a href="https://colab.research.google.com/github/jeff-ai-ml/neural-network/blob/main/multi_layer_perceptron_home_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
# Create your first MLP in Keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy

In [112]:
# fix random seed for reproducibility
numpy.random.seed(7)
# load pima indians dataset
dataset = numpy.loadtxt("https://raw.githubusercontent.com/jeff-ai-ml/ml-datasets/refs/heads/main/home.csv", delimiter=",")
# split into input (X) and output (Y) variables
#print(dataset)
X = dataset[:,0:2]
Y = dataset[:,2]

#print(X)

In [113]:
# Scale inputs
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Scale output (reshape required for scaler)
scaler_Y = StandardScaler()
Y = scaler_Y.fit_transform(Y.reshape(-1, 1))

In [115]:
# create model
model = Sequential()
model.add(Dense(3, input_dim=2, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1))
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_39 (Dense)                │ (None, 3)              │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_40 (Dense)                │ (None, 3)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 25 (100.00 B)

 Trainable params: 25 (100.00 B)

 Non-trainable params: 0 (0.00 B)

In [116]:
for i, layer in enumerate(model.layers):
    if hasattr(layer, 'kernel_initializer'):
        print(f"Layer {i} - {layer.name}:")
        print("  Kernel Initializer:", layer.kernel_initializer)
        print()


Layer 0 - dense_39:
  Kernel Initializer: <keras.src.initializers.random_initializers.GlorotUniform object at 0x7e8d88d75c50>

Layer 1 - dense_40:
  Kernel Initializer: <keras.src.initializers.random_initializers.GlorotUniform object at 0x7e8d88daee10>

Layer 2 - dense_41:
  Kernel Initializer: <keras.src.initializers.random_initializers.GlorotUniform object at 0x7e8d80efe9d0>



In [117]:
# Compile model
model.compile(loss='mse', optimizer='adam', metrics=['mse', 'mae'])
#model.compile(optimizer='adam', loss='mse')
print("\n📌 Initial Weights:")
for layer in model.layers:
    weights = layer.get_weights()
    if weights:
        print(f"Layer {layer.name} weights:\n", weights[0])
        print(f"Layer {layer.name} biases:\n", weights[1])


📌 Initial Weights:
Layer dense_39 weights:
 [[ 0.11222506  1.0278723  -0.3226335 ]
 [ 0.13292396 -0.8053798  -0.8505849 ]]
Layer dense_39 biases:
 [0. 0. 0.]
Layer dense_40 weights:
 [[-0.88409877  0.5400827   0.2138691 ]
 [ 0.25104618  0.5062475  -0.39439535]
 [-0.48986483  0.4871633  -0.2804489 ]]
Layer dense_40 biases:
 [0. 0. 0.]
Layer dense_41 weights:
 [[-0.29388416]
 [ 0.545678  ]
 [-1.0104827 ]]
Layer dense_41 biases:
 [0.]


In [104]:
# Fit the model

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

model.fit(X_train, Y_train, epochs=150, batch_size=10)
#evaluate the model
scores = model.evaluate(X_test, Y_test)
print(f"\nMSE: {scores[1]:.2f}, MAE: {scores[2]:.2f}")

Epoch 1/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.5806 - mae: 0.6090 - mse: 0.5806
Epoch 2/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6122 - mae: 0.6410 - mse: 0.6122
Epoch 3/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6121 - mae: 0.6144 - mse: 0.6121
Epoch 4/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5615 - mae: 0.5728 - mse: 0.5615
Epoch 5/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6131 - mae: 0.6400 - mse: 0.6131
Epoch 6/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6810 - mae: 0.6504 - mse: 0.6810
Epoch 7/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5913 - mae: 0.6089 - mse: 0.5913
Epoch 8/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6539 - mae: 0.6458 - mse: 0.6539
Epoch 9/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6896 - mae: 0.6067 - mse: 0.6896
Epoch 10/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6413 - mae: 0.5827 - mse: 0.6413
Epoch 11/150
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6744 - m

In [105]:
for layer in model.layers:
    print(f"Layer: {layer.name}")
    weights = layer.get_weights()
    if weights:
        print(f"  Weights shape: {weights[0].shape}")
        print(f"  Weights: \n{weights[0]}")
        print(f"  Biases shape: {weights[1].shape}")
        print(f"  Biases: \n{weights[1]}")
    else:
        print("  No weights (e.g., Dropout or Flatten layer)")


Layer: dense_27
  Weights shape: (2, 3)
  Weights: 
[[-0.520238    0.59853464  0.47542268]
 [-0.31195945  0.48228014  0.1046212 ]]
  Biases shape: (3,)
  Biases: 
[ 0.0779736  -0.15696946  0.13638376]
Layer: dense_28
  Weights shape: (3, 3)
  Weights: 
[[-0.24206638 -0.07035996  0.45568544]
 [ 0.01230264  0.18846393 -0.6028671 ]
 [-0.9723487   0.59998864 -0.83161515]]
  Biases shape: (3,)
  Biases: 
[ 0.         -0.00025655  0.10543218]
Layer: dense_29
  Weights shape: (3, 1)
  Weights: 
[[ 0.10224271]
 [ 1.3546197 ]
 [-1.3101343 ]]
  Biases shape: (1,)
  Biases: 
[-0.09926414]


In [106]:
all_weights = model.get_weights()
for i, param in enumerate(all_weights):
    print(f"Param {i} shape: {param.shape}\n{param}\n")


Param 0 shape: (2, 3)
[[-0.520238    0.59853464  0.47542268]
 [-0.31195945  0.48228014  0.1046212 ]]

Param 1 shape: (3,)
[ 0.0779736  -0.15696946  0.13638376]

Param 2 shape: (3, 3)
[[-0.24206638 -0.07035996  0.45568544]
 [ 0.01230264  0.18846393 -0.6028671 ]
 [-0.9723487   0.59998864 -0.83161515]]

Param 3 shape: (3,)
[ 0.         -0.00025655  0.10543218]

Param 4 shape: (3, 1)
[[ 0.10224271]
 [ 1.3546197 ]
 [-1.3101343 ]]

Param 5 shape: (1,)
[-0.09926414]



In [107]:
import numpy as np

# New house samples
samples = np.array([
    [1600, 3],   # Sample 1
    [1600, 2],   # Sample 2
    [1200, 2]    # Sample 3
])

In [108]:
# Apply the same scaling used during training
samples_scaled = scaler.transform(samples)

# Predict prices (scaled output)
predictions = model.predict(samples_scaled)

# Inverse transform to get original price values (scaled value will be less)
predictions_unscaled = scaler_Y.inverse_transform(predictions)

# Print the unscaled predictions
for i, price in enumerate(predictions_unscaled):
    print(f"Sample {i+1} predicted house price: ${price[0]:,.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
Sample 1 predicted house price: $280,498.41
Sample 2 predicted house price: $249,896.16
Sample 3 predicted house price: $230,348.84
